# prefix C-b → C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

set -sg escape-time 10

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g mouse on
set -g focus-events on

# keybinds
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

bind x kill-pane

## window split
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

## select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## resize pane
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

## copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# visual
set -g window-status-format "#[fg=colour245]#I:#W"
set -g window-status-current-format "#[bold]#I:#W"
setw -g window-status-style bg=default
setw -g window-status-current-style bg=default

set -g pane-border-style fg=#444444
set -g pane-active-border-style fg=#89b4fa

set -g status-style bg=default,fg=#cdd6f4
set -g status-position bottom
set -g status-left-length 40
set -g status-right-length 80

set -g status-left "#[fg=green] #S "
set -g status-right "#[fg=blue]#(cd '#{pane_current_path}' && git rev-parse --abbrev-ref HEAD 2>/dev/null) #[fg=yellow]%Y-%m-%d #[fg=cyan]%H:%M "


set -g history-limit 100000

set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}"
